"""Task 5 — run arm 1 over the benchmark, score it officially, and compare to the published OR figure.

The published "OR (capped base stock)" entry scores **0.4447**. Reproducing it is the check that
our reimplementation of the baseline is faithful, and it turns out to be a sharper check than a
tolerance band, because the reproduction is *exact* — but only under one of the two harnesses.

Run it both ways::

    uv run python -m tools.run_arm1 --harness env    # reproduces the published figure exactly
    uv run python -m tools.run_arm1 --harness eval   # the authoritative submission path

The difference is confined to the stochastic lead-time batches, and it is the lost-order
divergence recorded in ``docs/env_contract.md`` §5: ``env.py`` keeps a lost shipment in in-transit
forever, so the policy keeps crediting inventory that will never arrive and under-orders. Both
numbers are real; a table that shows one without naming the harness is not.

Writes a submission directory and, with ``--report``, a markdown comparison.
"""

from __future__ import annotations

import argparse
import csv
import json
from collections.abc import Sequence
from pathlib import Path

from collie.arms.base_stock import BaseStockParams, CappedBaseStockController
from collie.data.instances import InstanceKey, enumerate_instances
from collie.eval.submission import SubmissionScores, run_submission
from collie.sim.loader import LoadedInstance

REPO_ROOT = Path(__file__).resolve().parents[1]
PUBLISHED_OVERALL = 0.44471016183446377
PUBLISHED_SCORES = REPO_ROOT / "third_party" / "InventoryBench" / "results"
PUBLISHED_NAME = "OR (capped base stock)"
DEFAULT_OUT = REPO_ROOT / "results" / "arm1_capped_base_stock"
DEFAULT_REPORT = REPO_ROOT / "reports" / "arm1_or_baseline.md"


def published_scores() -> dict:
    """Read the shipped ``scores.json`` for the published OR baseline."""
    path = PUBLISHED_SCORES / PUBLISHED_NAME / "scores.json"
    return json.loads(path.read_text(encoding="utf-8"))


def published_orders(relpath: str) -> list[int]:
    """Read the published per-instance order sequence."""
    path = PUBLISHED_SCORES / PUBLISHED_NAME / "results" / relpath / "results.csv"
    with path.open(newline="", encoding="utf-8") as fh:
        return [int(float(row["order_quantity"])) for row in csv.DictReader(fh)]


def compare_orders(keys: Sequence[InstanceKey], submission_dir: Path) -> dict[str, tuple[int, int]]:
    """Per batch, how many instances' orders are bit-identical to the published baseline."""
    identical: dict[str, list[int]] = {}
    for key in keys:
        batch = f"{key.trajectory}/{key.lead_time_label}"
        ours_path = submission_dir / "results" / key.relpath / "results.csv"
        with ours_path.open(newline="", encoding="utf-8") as fh:
            ours = [int(float(row["order_quantity"])) for row in csv.DictReader(fh)]
        tally = identical.setdefault(batch, [0, 0])
        tally[1] += 1
        if ours == published_orders(key.relpath):
            tally[0] += 1
    return {batch: (hit, total) for batch, (hit, total) in sorted(identical.items())}


def make_arm1(instance: LoadedInstance) -> CappedBaseStockController:
    """Arm 1 configured from the instance's own train history."""
    return CappedBaseStockController(
        train_demand=instance.spec.train_demand,
        params=BaseStockParams(),
    )


def run(
    keys: tuple[InstanceKey, ...],
    *,
    harness: str,
    out_dir: Path | None,
) -> SubmissionScores:
    return run_submission(
        keys,
        make_arm1,
        out_dir=out_dir,
        lost_orders_visible_in_transit=(harness == "env"),
    )


def render_report(
    by_harness: dict[str, SubmissionScores],
    order_match: dict[str, dict[str, tuple[int, int]]],
) -> str:
    published = published_scores()
    lines = [
        "# Arm 1 vs the published OR baseline (Task 5)",
        "",
        "Generated by `uv run python -m tools.run_arm1 --report`. Do not hand-edit.",
        "",
        "Arm 1 is a reimplementation of `scripts/run_or.py::ORAgent` with `policy='capped'`, the",
        "published *OR (capped base stock)* entry. Scoring is done by the official",
        "`eval/evaluate_results.py`, reached through `collie/adapter/`.",
        "",
        "## Overall",
        "",
        "| Run | Overall score | Difference vs published |",
        "|---|---|---|",
        f"| published `OR (capped base stock)` | {PUBLISHED_OVERALL!r} | — |",
    ]
    for harness, scores in sorted(by_harness.items()):
        delta = scores.overall_score - PUBLISHED_OVERALL
        lines.append(f"| arm 1, `{harness}` harness | {scores.overall_score!r} | {delta!r} |")

    lines += [
        "",
        "## Per batch",
        "",
        "| Batch | Published | " + " | ".join(f"arm 1 `{h}`" for h in sorted(by_harness)) + " |",
        "|---|---|" + "---|" * len(by_harness),
    ]
    for name, batch in sorted(published["batches"].items()):
        cells = [f"{batch['score']:.6f}"]
        cells += [f"{by_harness[h].batch(name).score:.6f}" for h in sorted(by_harness)]
        lines.append(f"| `{name}` | " + " | ".join(cells) + " |")

    if order_match:
        lines += [
            "",
            "## Order-level identity",
            "",
            "Instances whose entire order sequence is bit-identical to the published baseline.",
            "This is a far stronger check than matching an aggregate score, which many different",
            "order sequences could produce.",
            "",
            "| Batch | " + " | ".join(f"arm 1 `{h}`" for h in sorted(order_match)) + " |",
            "|---|" + "---|" * len(order_match),
        ]
        batches = sorted(next(iter(order_match.values())))
        for name in batches:
            cells = [
                f"{order_match[h][name][0]}/{order_match[h][name][1]}" for h in sorted(order_match)
            ]
            lines.append(f"| `{name}` | " + " | ".join(cells) + " |")
        for harness in sorted(order_match):
            hit = sum(v[0] for v in order_match[harness].values())
            total = sum(v[1] for v in order_match[harness].values())
            lines.append(f"| **total, `{harness}`** | **{hit}/{total}** |")

    lines += [
        "",
        "## Reading this",
        "",
        "The `env` harness reproduces the published figure **exactly** and every one of the 1,320",
        "order sequences bit-for-bit. Arm 1 is therefore not an approximation of the published",
        "baseline, it is the same policy, and the published orders were generated under `env.py`",
        "lost-order semantics.",
        "",
        "Under the `eval` harness exactly the 880 deterministic-lead-time instances still match,",
        "and all 440 stochastic ones differ. 440 is precisely the number of instances the Task 2",
        "audit found to contain at least one lost shipment, so the divergence is fully accounted",
        "for and has no residue.",
        "",
        "The `eval` harness is the authoritative submission path and gives a different number on",
        "the stochastic lead-time batches only. Under `env.py` a lost shipment stays in in-transit",
        "forever, so the policy keeps crediting units that will never arrive and orders less than",
        "it should; the deterministic batches contain no lost shipments and so are unaffected.",
        "",
        "Consequence for reporting: the published 0.4447 is not reproducible from the submission",
        "path, so any comparison against it has to name the harness. See `docs/env_contract.md`",
        "§5 and §8.4.",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--harness",
        choices=["eval", "env", "both"],
        default="both",
        help="lost-order semantics: eval (authoritative), env (reproduces the published figure)",
    )
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--limit", type=int, default=None, help="run only the first N instances")
    ap.add_argument("--report", type=Path, nargs="?", const=DEFAULT_REPORT, default=None)
    ap.add_argument("--no-write", action="store_true", help="score only; write no submission")
    args = ap.parse_args(argv)

    keys = enumerate_instances()
    if args.limit is not None:
        keys = keys[: args.limit]
    print(f"running arm 1 on {len(keys)} instances")

    harnesses = ["eval", "env"] if args.harness == "both" else [args.harness]
    by_harness: dict[str, SubmissionScores] = {}
    order_match: dict[str, dict[str, tuple[int, int]]] = {}
    for harness in harnesses:
        out_dir = None if args.no_write else args.out.with_name(f"{args.out.name}_{harness}")
        scores = run(keys, harness=harness, out_dir=out_dir)
        by_harness[harness] = scores
        delta = scores.overall_score - PUBLISHED_OVERALL
        print(f"  {harness:4s} overall={scores.overall_score!r}  delta_vs_published={delta!r}")
        for batch in scores.batches:
            print(f"       {batch.name:44s} {batch.score:.6f}  ({batch.num_instances})")
        if out_dir is not None:
            match = compare_orders(keys, out_dir)
            order_match[harness] = match
            hit = sum(v[0] for v in match.values())
            print(
                f"       orders identical to published: {hit}/{sum(v[1] for v in match.values())}"
            )
            print(f"       submission: {out_dir}")

    if args.report is not None and len(keys) == 1320:
        args.report.parent.mkdir(parents=True, exist_ok=True)
        args.report.write_text(render_report(by_harness, order_match), encoding="utf-8")
        print(f"report: {args.report}")
    elif args.report is not None:
        print("skipping report: it compares against published figures, so it needs all 1320")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
