"""Task 4 — select and commit the instance list for the accounting-equivalence suite.

The list is committed rather than recomputed at test time so that the equivalence claim refers to
a fixed set of instances. If the benchmark pin moves, this tool is re-run deliberately and the
diff shows exactly which instances entered or left the evidence base.

Selection is stratified over the 18 ``(trajectory, lead_time, cost_ratio)`` cells and picked by
even stride, so it is reproducible with no RNG involved. Twelve per cell gives 216 instances,
clearing the 200 the plan calls for while keeping every cell equally weighted; the smallest cell
in the shipped benchmark holds 55, so no cell is short.

Usage::

    uv run python -m tools.select_equivalence_set --out manifests/equivalence_instances.txt
"""

from __future__ import annotations

import argparse
import json
from collections import Counter
from pathlib import Path

from collie.data.instances import enumerate_instances, stratified_sample

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUT = REPO_ROOT / "manifests" / "equivalence_instances.txt"
MANIFEST = REPO_ROOT / "manifests" / "benchmark_v1.json"
PER_CELL = 12
MIN_REQUIRED = 200


def benchmark_commit() -> str:
    """Read the pin from the Task 2 manifest, so there is one recorded source for it."""
    try:
        return json.loads(MANIFEST.read_text(encoding="utf-8"))["benchmark_commit"]
    except (OSError, KeyError, json.JSONDecodeError):
        return "unknown"


def render(per_cell: int = PER_CELL) -> str:
    keys = enumerate_instances()
    selected = stratified_sample(keys, per_cell=per_cell)
    if len(selected) < MIN_REQUIRED:
        raise SystemExit(
            f"selected {len(selected)} instances, fewer than the {MIN_REQUIRED} required. "
            f"Raise --per-cell (currently {per_cell})."
        )
    by_cell = Counter(k.cell for k in selected)
    lines = [
        "# COLLIE Task 4 accounting-equivalence instance set.",
        "# Generated by: uv run python -m tools.select_equivalence_set",
        "# Do not hand-edit. Regenerating is a deliberate act; the diff is the audit trail.",
        f"# benchmark_commit: {benchmark_commit()}",
        f"# population: {len(keys)} instances",
        f"# selected: {len(selected)} instances, {per_cell} per cell, {len(by_cell)} cells",
        "# strata: (trajectory, lead_time_label, cost_ratio_label)",
        "#   cost_ratio_label is the MARGIN: high=profit 19, med=profit 4, low=profit 1.",
        "#   holding cost is 1.0 in every instance, so 'low' is the punishing case.",
        "# selection: even stride over each sorted cell. No RNG.",
    ]
    for cell, count in sorted(by_cell.items()):
        lines.append(f"#   {'/'.join(cell)}: {count}")
    lines.extend(k.relpath for k in selected)
    return "\n".join(lines) + "\n"


def load_selection(path: Path | None = None) -> tuple[str, ...]:
    """Read the committed list, dropping comments. Used by the equivalence suite."""
    target = path or DEFAULT_OUT
    if not target.is_file():
        raise FileNotFoundError(
            f"{target} is missing. Generate it with: uv run python -m tools.select_equivalence_set"
        )
    return tuple(
        line.strip()
        for line in target.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.startswith("#")
    )


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--per-cell", type=int, default=PER_CELL)
    ap.add_argument(
        "--check",
        action="store_true",
        help="fail if the committed file differs from a fresh render, and write nothing",
    )
    args = ap.parse_args(argv)

    text = render(args.per_cell)
    if args.check:
        current = args.out.read_text(encoding="utf-8") if args.out.is_file() else ""
        if current != text:
            raise SystemExit(f"{args.out} is stale. Re-run without --check.")
        print(f"{args.out} is up to date ({len(load_selection(args.out))} instances)")
        return 0

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text, encoding="utf-8")
    print(f"wrote {args.out} ({len(load_selection(args.out))} instances)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
